language: node_js
node_js:
- 8.11.2
sudo: required
cache:
  npm: true
  directories:
  - "/home/travis/.cache/Cypress"
  - "~/.npm"
install:
- npm install
- npm install -g ngrok
before_script:
- PATH=${PATH//:\.\/node_modules\/\.bin/}
- mkdir public
- curl -sO http://stedolan.github.io/jq/download/linux64/jq
- ngrok authtoken ${NGROK_AUTH_TOKEN} > /dev/null &
- ngrok http file://$(pwd)/public/ --authtoken=${NGROK_AUTH_TOKEN}
- sleep 3
script:
- echo "themey@runbox.com" | npm run lint
- echo {} > credentials.json
- npm run format
- npm run build && npm run zip
- NGROK_PATH=$(curl 'http://127.0.0.1:4040/api/tunnels' | jq -r '.tunnels[0].public_url')/theme.zip
- echo "{\"theme\":{\"name\":\"Travis Curl Test - $(date +"%D %T %Z")\",\"src\":\"$NGROK_PATH\"}}"
  > body.json
- echo $(cat body.json)
- 'TEST_THEME_ID=$(curl -d @body.json -H "Accept: application/json" -H "Content-Type:
  application/json" https://${SHOPIFY_API_KEY}:${SHOPIFY_API_PASSWORD}@${SHOPIFY_URL}/admin/api/2019-07/themes.json
  | jq -r ''.theme.id'')'
- echo ${TEST_THEME_ID}
- if [ ${TEST_THEME_ID} == null ] ; then exit 1 ; fi
- while [ $(curl https://${SHOPIFY_API_KEY}:${SHOPIFY_API_PASSWORD}@${SHOPIFY_URL}/admin/api/2019-04/themes/$TEST_THEME_ID.json
  | jq -r '.theme.previewable') != 'true' ]; do echo 'Waiting for theme'; sleep 2;
  done
- cypress run --env SHOPIFY_URL=${SHOPIFY_URL},SHOPIFY_THEME_ID=$TEST_THEME_ID
- 'curl -H "Accept: application/json" -X DELETE https://${SHOPIFY_API_KEY}:${SHOPIFY_API_PASSWORD}@${SHOPIFY_URL}/admin/api/2019-07/themes/$TEST_THEME_ID.json'
addons:
  chrome: stable
  apt:
    packages:
    - libgconf-2-4
notifications:
  email: false
  slack:
    secure: RvPL7N56A4CGjVaMdqm2Mcz9pPum7qDr1sn8lvSQvZdz0gHCA4340vhwbC+Ca7BpObE6hGGadsO6FrPVs6PXYQoISm5AW/WkSDmgKKebMxRrHqLrwmtn6Y3/jxNlIWsF5vaz8R/Teq204CGRclUMONfJHw7YbmNt7Qco2OYjU2BpRZo9DZ360nSWYFHa+Ohngh2hMHGWpQVBsYl5tayiy8l8C1/TPKU+Yo5j6rvmzAOviSd0mQtPiwWO5q7exJUJpoX0GKUK4vMFrrBSNdX9Q2LoCNH8RI9br58hHv3s2jeO06rEYV3txVhUViBrNwRY6SNv4Fy0eqFkstXJIXUy7nPVV10lkt/6vd9iRaW5Vansl4TMG4gP5wNRSiMqldxgntXT0geyHGFZezi1sO/wy5JJ7QtPzrLtR/7OpzOHfcHfEI9fvB2GH8/5Vs4vBBKT0rDf30nuhEbGlcvPWMIAnUVAMu6fmp7tdQtmYZC3pBhYAdVbnsddHF0yXcCvSSLUKOUWyxOwIqcjughFmoAzKlrDCl42MX2wohHNJr9ZDhYuu1e2eaVQ8ypg+Tkh6Ss/4lBjHrHFgF+YYoN1rTokA6ChCiTw8r8VEitrHkL/GT1vQKRvHr+f+PbbAfV4FCdLbv/k6OytMnsoPhmAQJ6tAcEbVqgiQouFaKN4Oh3PpeQ=
    on_success: change
    on_pull_requests: false
    template:
    - "%{repository_slug} (%{commit}) : %{message}"
    - 'Build details: %{build_url}'
env:
  global:
  - SHOPIFY_URL: greenstore-dev.myshopify.com
  - secure: aYxpjQ6Ock33RrQkRb+agBrBuG3iZIJPO5zIfqj7SMXe9EwBpU3GYYXCjywKu7y4dfqUENg6RWoJ4RJ/6cRSZXo3otOpjgkgGQI9DdlOZo0E2e9mxo90culkNrliebg6jZ1diiB4XrzWOvsg+XD2FsmOUET6xDEBm5g+ZssjSrftLkfXf3kue7UTTSNgUEFegVGDEPjYok+DFl9SpW3b1YL82s53pZm3Rilf7O1Av0EngwnsndAksBsKH64FUCi5h4mkGU+CjaZVODnEU5d6UdHTgthWbjtwQzJV26yAUeU+lTUg7NrnwLrzsnPe5us1YSQ5kOMI9f3MlpBBY748rAXxu9bvgduFaT4Por46HCFNuQw64UatpqsxNuFZFc71neBXJ8hYKDYT/sJhTyeT9paUrrFsgPjsl7850AgOC016RFZQqThEVUgEFTcqFgGlN7uzBFo3mygVh1Tx15e14qsO0HVGRBYY6299/ZWzLXkQvvhfC6R93zj4K3/pbUb4hc/gqa0FOCt0rCYLbce+b11LIQocibcPF9FC7lawW4STpx7VmKQDrq+Dn4Ype4fC1RHLG81+Sjr80Gg0GZ+5SIwCHI5NILjf7EfHb1exk1wyiiS0BtkxPgXkVj4IJwwKc9tvsZP1MdUVza4mrhPbSSUuETU0t8Yd3gHgsLVbugA=
  - secure: IeUw7hk44grp2JT0YfXqEOyJhbD3GKLWhmWo5+4OnMkdjkussfBrpwgLzLL1wqb9RQx7Q5Uip3kzm6uV+ckrwmh81fLfTbTKVSXCXk4+af1IcpdkxbRQYOHeS6kZ/5ElcLokdCWsHPxFNSWapnXBFIpElNGKCIC2Cw4CyW68Mjh2W7bWVOEGqy/70c9vNnts6pnqH+TQueb9adV9YMNn1eFJiB3qi9T35v8cEbunGFLN7kcK3EPlV8fOhPHgS+NZUQHxsfnC5SRK880wdR4H5L95ed9nBvD0hWKtx6ue81Uu/5jYZ1IBCdhyucKPPX47XWfFNNC68jcg4xCzbFDM7xnbaysV0K4q1Kwv6ur2fYvdLWtjiS0HX5cqes5JltuV3Tba3ifbV/3boeZj5qLBu4fHBdo7WCejnWwh075bozf1Uhp0wXdN/ggBkQlSRobACNsDKYEYdY+keuQLnChu48HwhZOQ1K+Z+JAHZIdpFoWV3NEe0q/79E8F8C5snyJSp2kWHr311j9D3cWVRBdMc+XA1p5Yka0HYOFqwtaONBaoaBavaasAHRJpqdU7917C57tx2Z9aWdoVXkA4gtJVx2vvVvt8eyTomXKBa5d2IcHTmpPoRjhfHkkBLqCMINlwPCXVgiv+sBk1+c4cmawA8M2i2xvwpi3gzBmTdtNWtIc=
  - secure: Ig66DChDRUxypAjlNC8HC8KmhAbcfhQWp9/FumreVsq6ThH76p3UTN4J9mV9vJei579lOCrvHS70+TnIfWH9/wnfHCS4Zf5sR+jc0DaAcc58I0eyzRVx1THO9vol4bujqXu/MTS2grFVSrkqC/anTN7UslY1F3Yf4UX6f7cHSjS4sPnweJ+JtIB1sdo+PCqhlxgLMe+pZytYokFkrejXAPhZQyjm0NUUG6jL7dmu4A7K+mleCMMOyYX3Hl/cVy+OJ2LP4IIYYWuycpVU/ZHLHOfN0Xzd9DflPS9tqSu2wg4r24C7QU6/LnLwUdMKWkbxj/MnJ3kQu4Slr/qOEVaqCwo/JH9NC5Y1WS0SaqRrzF1LeN+oxzWut7V2KosDCEzDobk+dNTxW+978Fo/9thm+LTy0E4dnat24t9ghAMrL9RRwFC7KXrgm69umXM7imc12etPoZTh7LlAJ97bTpjGungjEB+IgwF3dSStnJgfpN/cNCA06Qk/0PeMiqKpU5k2y+laYpvv6l4Jlt6kP83w/x9bvv6qpOKd9WTVxGw2yx1XlJ/YMXeRTTClYj7oV3YEseojk8qRSoF8UqH1tJ190nz0HSrWzG6dYZxGVcF8RhGRmLmF7D7MA3vsa9xhxoNjpafyNPn4w31u7J7aOqYsdPCjRyExmh8blXtkpAQ8PPQ=
